### ISSUE TITLE
Can not display rotate controller

### ISSUE THREAD

**Issue by jaredhan418** [wassim-k/mapbox-gl-draw-scale-rotate#1]
<img width="369" alt="截屏2024-03-28 18 50 37" src="https://github.com/wassim-k/mapbox-gl-draw-scale-rotate/assets/11781874/a2816737-1e59-4c0b-a9c2-9bdc2d459156">
<img width="238" alt="截屏2024-03-28 18 52 52" src="https://github.com/wassim-k/mapbox-gl-draw-scale-rotate/assets/11781874/5216d420-94f5-487d-9f9a-14ab98bfd815">

featureid is string but geojson id is number

**Comment by wassim-k** [comment]
`mapbox-gl-draw-sale-rotate` is a plugin for [mapbox-gl-draw](https://github.com/mapbox/mapbox-gl-draw) so it must be compliant with their [API](https://github.com/mapbox/mapbox-gl-draw/blob/main/docs/API.md#changemodemode-string-options-object-draw) which only uses strings for feature ids.

**Comment by jaredhan418** [comment]
Yes, you are right. featureId must string, but `geoJson.properties.id` could be number.
<img width="888" alt="截屏2024-04-03 22 32 40" src="https://github.com/wassim-k/mapbox-gl-draw-scale-rotate/assets/11781874/d6f2b51d-ef6d-4072-9835-490604cb0275">

**Comment by wassim-k** [comment]
This behavior is consistent with [mapbox-gl-draw](https://github.com/mapbox/mapbox-gl-draw/) implementation [here](https://github.com/mapbox/mapbox-gl-draw/blob/main/src/modes/direct_select.js#L151)

If you feel like this behavior is incorrect then please raise an issue with [mapbox-gl-draw](https://github.com/mapbox/mapbox-gl-draw/) and if they change it then I'll happily make the same change here.
